{% set version = "2.0.4" %}

package:
  name: paramnb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/paramnb/paramnb-{{ version }}.tar.gz
  sha256: 202240be9e290c3eba1e7e0a0563d10184634c87a8faabffa348baa3e8ad36cc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - pyct-core >=0.4.4
  run:
    - python >={{ python_min }}
    - param >=1.7.0
    - ipywidgets >=5.2.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - paramnb

about:
  home: https://github.com/ioam/paramnb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Generate ipywidgets from Parameterized objects in the notebook
  doc_url: https://paramnb.pyviz.org/
  dev_url: https://github.com/ioam/paramnb

extra:
  recipe-maintainers:
    - ocefpaf
